/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author Albert
 */
public class mainPHL extends javax.swing.JFrame {

    /**
     * Creates new form mainPHL1
     */
    public mainPHL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Usuarios = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        MascotasR = new javax.swing.JMenuItem();
        MascotasC = new javax.swing.JMenuItem();
        MascotasA = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        SolicitudesA = new javax.swing.JMenuItem();
        SolicitudesE = new javax.swing.JMenuItem();
        Inventario = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Bienvenido a PetHouse Lite AFAD:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 204));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(535, 150000));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(594, 70));

        Usuarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Usuarios.setText("Usuarios Registrados");
        Usuarios.setBorderPainted(true);
        Usuarios.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Usuarios.setMaximumSize(new java.awt.Dimension(250, 32767));
        jMenuBar1.add(Usuarios);

        jMenu2.setBackground(new java.awt.Color(255, 255, 204));
        jMenu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jMenu2.setText("Mascotas Registradas");
        jMenu2.setBorderPainted(true);
        jMenu2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jMenu2.setMaximumSize(new java.awt.Dimension(250, 32767));

        MascotasR.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        MascotasR.setText("Mascotas de Resguardadas");
        MascotasR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MascotasR.setBorderPainted(true);
        MascotasR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MascotasRActionPerformed(evt);
            }
        });
        jMenu2.add(MascotasR);

        MascotasC.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        MascotasC.setText("Mascotas de Cliente");
        MascotasC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MascotasC.setBorderPainted(true);
        MascotasC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MascotasCActionPerformed(evt);
            }
        });
        jMenu2.add(MascotasC);

        MascotasA.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        MascotasA.setText("Mascotas Adoptadas");
        MascotasA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MascotasA.setBorderPainted(true);
        MascotasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MascotasAActionPerformed(evt);
            }
        });
        jMenu2.add(MascotasA);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jMenu3.setText("Solicitudes");
        jMenu3.setBorderPainted(true);
        jMenu3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jMenu3.setMaximumSize(new java.awt.Dimension(150, 32767));

        SolicitudesA.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        SolicitudesA.setText("Solicitudes de Adopción");
        SolicitudesA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SolicitudesA.setBorderPainted(true);
        jMenu3.add(SolicitudesA);

        SolicitudesE.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        SolicitudesE.setText("Solicitudes de Esterilización");
        SolicitudesE.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SolicitudesE.setBorderPainted(true);
        SolicitudesE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitudesEActionPerformed(evt);
            }
        });
        jMenu3.add(SolicitudesE);

        jMenuBar1.add(jMenu3);

        Inventario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Inventario.setText("Inventario");
        Inventario.setBorderPainted(true);
        Inventario.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Inventario.setMaximumSize(new java.awt.Dimension(150, 140000));
        Inventario.setPreferredSize(new java.awt.Dimension(101, 70));
        jMenuBar1.add(Inventario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SolicitudesEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitudesEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SolicitudesEActionPerformed

    private void MascotasRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MascotasRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MascotasRActionPerformed

    private void MascotasCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MascotasCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MascotasCActionPerformed

    private void MascotasAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MascotasAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MascotasAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPHL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPHL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPHL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPHL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPHL().setVisible(true);
            }
        });
    }

    public JMenu getInventario() {
        return Inventario;
    }

    public JMenuItem getMascotasA() {
        return MascotasA;
    }

    public JMenuItem getMascotasC() {
        return MascotasC;
    }

    public JMenuItem getMascotasR() {
        return MascotasR;
    }

    public JMenuItem getSolicitudesA() {
        return SolicitudesA;
    }

    public JMenuItem getSolicitudesE() {
        return SolicitudesE;
    }

    public JMenu getUsuarios() {
        return Usuarios;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Inventario;
    private javax.swing.JMenuItem MascotasA;
    private javax.swing.JMenuItem MascotasC;
    private javax.swing.JMenuItem MascotasR;
    private javax.swing.JMenuItem SolicitudesA;
    private javax.swing.JMenuItem SolicitudesE;
    private javax.swing.JMenu Usuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
